# Default embeddings configuration
model_ckpt: 'facebook/esm2_t33_650M_UR50D'
esm2_max_residues: 1022
# max_length: 512  # that's usually max residues + 2 for the special tokens
batch_size: 64
# device: 'auto'  # auto, cpu, cuda

# MODEL_CKPT = 'facebook/esm2_t6_8M_UR50D'    # embedding dim: 320D
# MODEL_CKPT = 'facebook/esm2_t12_35M_UR50D'  # embedding dim: 480D
# MODEL_CKPT = 'facebook/esm2_t30_150M_UR50D' # embedding dim: 640D
# MODEL_CKPT = 'facebook/esm2_t33_650M_UR50D' # embedding dim: 1280D
# MODEL_CKPT = 'facebook/esm2_t36_3B_UR50D'   # embedding dim: 2560D
# MODEL_CKPT = 'facebook/esm2_t48_15B_UR50D'  # embedding dim: 5120D

# Embedding generation parameters
pooling: 'mean'  # Pooling method: 'mean', 'max', 'cls', 'attention'
layer: 'last'  # Layer selection: 'last', 'second_last', or int (layer index)
emb_storage_precision: 'fp16'  # Storage precision: 'fp16' (recommended, 2 bytes), 'fp32' (4 bytes, full precision)
