# Default embeddings configuration
model_ckpt: 'facebook/esm2_t33_650M_UR50D'
esm2_max_residues: 1022
# max_length: 512  # that's usually max residues + 2 for the special tokens
batch_size: 32
# device: 'auto'  # auto, cpu, cuda