# Dataset configuration for segment pairs
# This config defines parameters for creating train/val/test splits and protein pairs

# Task name for output directory
# task_name: 'segment_pair_classifier' # TODO: we currently don't use this

# Isolate partitioning strategy
hard_partition_isolates: true  # true = partition isolates into train/val/test sets, false = partition proteins into train/val/test sets

# Protein filtering strategy
use_selected_only: true  # true = use selected_functions, false = use all proteins
max_isolates_to_process: null  # null = use all isolates; int = deterministic isolate sampling

# Plotting / post-processing
generate_visualizations: true  # If true, generate dataset plots after dataset creation

# Pair construction mode
# - unordered: original behavior (pairs are conceptually undirected; optional hash-based canonicalization can be applied)
# - schema_ordered: force slot semantics by function schema (func_left -> *_a, func_right -> *_b)
#                  This is an experimental/validation mode to remove "direction" as a free variable for directed features.
pair_mode: unordered
# Required when pair_mode=schema_ordered. Order is semantic; do NOT sort.
# Example: ["HA", "NA"]
schema_pair: null

# Pair orientation canonicalization
# The segment-matching task is conceptually undirected (a,b) ≡ (b,a), but we store directed columns
# (*_a/*_b) and feed the model a directed representation (e.g., [emb_a, emb_b]).
# Canonicalizing orientation helps prevent "direction → label" shortcut learning.
canonicalize_pair_orientation: true

# Dataset splitting parameters
neg_to_pos_ratio: 1.0  # Ratio of negative to positive pairs
allow_same_func_negatives: false  # Allow same-function negative pairs (e.g., RdRp vs RdRp)
max_same_func_ratio: 0.5  # Maximum fraction of same-function negative pairs; not used when allow_same_func_negatives=false

# Train/validation/test split ratios
train_ratio: 0.8  # 80% for training
val_ratio: 0.1    # 10% for validation (test gets remaining 10%)

# Label shuffling (for sanity tests)
shuffle_train_labels: false  # If true, randomly shuffle training labels (val/test unchanged)
shuffle_train_labels_seed: null  # Seed for label shuffling (null = use RANDOM_SEED)

# Metadata filtering (Optional. Filter isolates by host, year, H/N subtype, etc.)
# If any of these are specified, metadata will be enriched and isolates filtered
host: null      # null = no filter, or "Human", "Pig", "Chicken", etc.
year: null      # null = no filter, or integer year (e.g., 2020)
hn_subtype: null # null = no filter, or "H1N1", "H3N2", etc.
geo_location: null  # null = no filter, or geographic location name (e.g., "Illinois")
passage: null   # null = no filter, or passage value (e.g., "Original", "S1", "Egg")

# Cross-validation
# n_folds: null = single-split mode (default); int N = generate N CV folds in one dataset run
# fold_id: used by launchers to select which fold dir to pass to the training script; null = ignored
n_folds: null
fold_id: null
