"""
Metadata enrichment utility.

This module provides functions to enrich protein dataframes with metadata
(hn_subtype, host, year) for metadata filtering experiments.

Note: flu_genomes_metadata_parsed.csv is generated by flu_genomes_eda.py script.
"""

import time
import pandas as pd
from pathlib import Path
from typing import Optional


def load_flu_metadata(
    metadata_file: Optional[Path] = None,
    project_root: Optional[Path] = None) -> pd.DataFrame:
    """
    Load flu metadata from processed CSV file.
    
    Args:
        metadata_file: Path to metadata CSV file. If None, uses default location.
        project_root: Project root directory. If None, infers from file location.
    
    Returns:
        DataFrame with columns: assembly_id, host, year, hn_subtype, ...
    """
    if metadata_file is None:
        if project_root is None:
            # Infer project root from this file's location
            project_root = Path(__file__).resolve().parents[2]
        metadata_file = project_root / "data" / "processed" / "flu" / "metadata_eda" / "flu_genomes_metadata_parsed.csv"

    if not metadata_file.exists():
        raise FileNotFoundError(f"Metadata file not found: {metadata_file}")

    meta = pd.read_csv(metadata_file)

    # Upstream key is `hash_id`; the rest of the pipeline keys on `assembly_id` (same value).
    meta = meta.rename(columns={'hash_id': 'assembly_id'})
    meta['assembly_id'] = meta['assembly_id'].astype(str)

    # Cast types: year to int, hn_subtype and host to str
    if 'year' in meta.columns:
        # Convert to numeric first (handles strings), then to Int64 (nullable integer type)
        meta['year'] = pd.to_numeric(meta['year'], errors='coerce').astype('Int64')
    if 'hn_subtype' in meta.columns:
        meta['hn_subtype'] = meta['hn_subtype'].astype(str)
        meta['hn_subtype'] = meta['hn_subtype'].replace('nan', pd.NA) # Replace 'nan' str with actual NaN
    if 'host' in meta.columns:
        meta['host'] = meta['host'].astype(str)
        meta['host'] = meta['host'].replace('nan', pd.NA) # Replace 'nan' str with actual NaN

    return meta


def enrich_prot_data_with_metadata(
    prot_df: pd.DataFrame,
    metadata_file: Optional[Path] = None,
    project_root: Optional[Path] = None
    ) -> pd.DataFrame:
    """
    Enrich protein dataframe with metadata (host, year, hn_subtype, location, passage).

    Args:
        prot_df: DataFrame with 'assembly_id' column
        metadata_file: Path to metadata CSV file. If None, uses default location.
        project_root: Project root directory. If None, infers from file location.

    Returns:
        Enriched DataFrame with additional columns: host, year, hn_subtype,
        geo_location_clean, passage
    """
    meta = load_flu_metadata(metadata_file, project_root)

    required_meta_cols = ['hn_subtype', 'host', 'year']
    meta_cols = ['assembly_id'] + required_meta_cols
    if 'geo_location_clean' in meta.columns:
        meta_cols.append('geo_location_clean')
    if 'passage' in meta.columns:
        meta_cols.append('passage')

    enriched_df = prot_df.merge(
        meta[meta_cols],
        on='assembly_id',
        how='left'
    )

    n_missing = enriched_df[required_meta_cols].isnull().any(axis=1).sum()
    n_total = len(enriched_df)
    if n_missing > 0:
        print(f"WARNING: {n_missing:,} out of {n_total:,} protein records ({100*n_missing/n_total:.1f}%) "
              f"have missing at least one of the required metadata: {required_meta_cols}.")

    return enriched_df
