"""
Metadata enrichment utility.

This module provides functions to enrich protein dataframes with metadata
(host, year, hn_subtype) for metadata filtering experiments.

Note: flu_genomes_metadata_parsed.csv is generated by flu_genomes_eda.py script.
"""

import pandas as pd
from pathlib import Path
from typing import Optional


def load_flu_metadata(
    metadata_file: Optional[Path] = None,
    project_root: Optional[Path] = None) -> pd.DataFrame:
    """
    Load flu metadata from processed CSV file.
    
    Args:
        metadata_file: Path to metadata CSV file. If None, uses default location.
        project_root: Project root directory. If None, infers from file location.
    
    Returns:
        DataFrame with columns: hash_id, host, year, hn_subtype, ...
    """
    if metadata_file is None:
        if project_root is None:
            # Infer project root from this file's location
            project_root = Path(__file__).resolve().parents[2]
        metadata_file = project_root / "data" / "processed" / "flu" / "metadata_eda" / "flu_genomes_metadata_parsed.csv"
    
    if not metadata_file.exists():
        raise FileNotFoundError(f"Metadata file not found: {metadata_file}")
    
    meta = pd.read_csv(metadata_file)
    
    # Ensure hash_id is string (for consistent merging)
    meta['hash_id'] = meta['hash_id'].astype(str)
    
    # Cast types: year to int, hn_subtype and host to str
    if 'year' in meta.columns:
        # Convert to numeric first (handles strings), then to Int64 (nullable integer type)
        meta['year'] = pd.to_numeric(meta['year'], errors='coerce').astype('Int64')
    if 'hn_subtype' in meta.columns:
        meta['hn_subtype'] = meta['hn_subtype'].astype(str)
        # Replace 'nan' strings with actual NaN
        meta['hn_subtype'] = meta['hn_subtype'].replace('nan', pd.NA)
    if 'host' in meta.columns:
        meta['host'] = meta['host'].astype(str)
        # Replace 'nan' strings with actual NaN
        meta['host'] = meta['host'].replace('nan', pd.NA)
    
    return meta


def enrich_prot_data_with_metadata(
    prot_df: pd.DataFrame,
    metadata_file: Optional[Path] = None,
    project_root: Optional[Path] = None
    ) -> pd.DataFrame:
    """
    Enrich protein dataframe with metadata (host, year, hn_subtype, location, passage).
    
    Since assembly_id == hash_id, we can directly map them.
    
    Args:
        prot_df: DataFrame with 'assembly_id' column
        metadata_file: Path to metadata CSV file. If None, uses default location.
        project_root: Project root directory. If None, infers from file location.
    
    Returns:
        Enriched DataFrame with additional columns: hash_id, host, year, hn_subtype, 
        geo_location_clean, passage
    """
    # Load meta
    meta = load_flu_metadata(metadata_file, project_root)

    # Create hash_id from assembly_id (they are the same)
    prot_df = prot_df.copy()
    prot_df['hash_id'] = prot_df['assembly_id'].astype(str)

    # Merge with meta (include geo_location_clean and passage if available)
    meta_cols = ['hash_id', 'host', 'year', 'hn_subtype']
    if 'geo_location_clean' in meta.columns:
        meta_cols.append('geo_location_clean')
    if 'passage' in meta.columns:
        meta_cols.append('passage')
    
    enriched_df = prot_df.merge(
        meta[meta_cols],
        on='hash_id',
        how='left'
    )

    # Report missing meta
    required_meta_cols = ['host', 'year', 'hn_subtype']
    n_missing = enriched_df[required_meta_cols].isnull().any(axis=1).sum()
    n_total = len(enriched_df)
    if n_missing > 0:
        print(f"⚠️  {n_missing:,} out of {n_total:,} protein records ({100*n_missing/n_total:.1f}%) "
              f"have missing metadata (host, year, or hn_subtype)")

    return enriched_df
