# Bunya bundle
# Contains virus-specific overrides
defaults:
  - /virus: bunya
  - /paths: bunya
  - /embeddings: default
  - /dataset: default
  - /training: base
  - _self_

# ===================================================================
# DIRECTORY NAMING
# ===================================================================
# Optional manual directory suffix - set this to create a specific output directory
# - null: Auto-generate suffix from max_isolates_to_process and seed
# - string: Use this exact suffix (e.g., '_v2', '_seed_42_GTOs_2000')

# run_suffix: "_v2"
run_suffix: null

# ===================================================================
# SEED MANAGEMENT
# ===================================================================
# Hierarchical seed system for reproducibility:
# - master_seed: Single seed that generates all process-specific seeds
# - process_seeds: Override specific stages (null = derive from master_seed)
# 
# Examples:
#   master_seed: 42, seed for all other process: null → use derived seed for all processes
#   master_seed: 42, process_seeds.preprocessing: 123 → preprocessing uses 123
#   master_seed: null, process_seeds.preprocessing: 42 → only preprocessing reproducible
#   master_seed: null → all processes use random seeds (non-reproducible)
#
# See docs/SEED_SYSTEM.md for detailed documentation

master_seed: 42  # Master seed for the entire experiment (null = random)

# Process-specific seeds (null = derive from master_seed)
process_seeds:
  preprocessing: null  # Data sampling and preprocessing
  embeddings: null     # ESM-2 embedding computation
  dataset: null        # Dataset splitting and augmentation
  training: null       # Model training and initialization
  evaluation: null     # Evaluation sampling and metrics

# ===================================================================
# DATA SAMPLING
# ===================================================================
# Controls how many isolates to process from the raw data directory

max_isolates_to_process: null  # null = full dataset, or set to 100, 500, etc.

# ====================================================================
# PROTEIN SELECTION
# ====================================================================
# For Bunya, use only the core proteins (L, M, S)
virus:
  selected_functions:
    - "RNA-dependent RNA polymerase"  # L segment
    - "Pre-glycoprotein polyprotein GP complex"  # M segment  
    - "Nucleocapsid protein"  # S segment

# ====================================================================
# MODEL AND DATASET OVERRIDES
# ====================================================================
# Embeddings overrides
embeddings:
  batch_size: 32
  use_selected_only: false # Compute embeddings for all proteins (since Bunya is a small dataset)

# Dataset overrides
dataset:
  use_selected_only: true  # Use selected_functions (a subset of protein functions)
  # neg_to_pos_ratio: 1.0  # Ratio of negative to positive pairs; default is 3.0
  allow_same_func_negatives: true  # Allow same-function negative pairs
  max_same_func_ratio: 0.5  # Maximum fraction of same-function negative pairs

# Training overrides
training:
  use_diff: true
  use_prod: true
  batch_size: 16
  learning_rate: 0.001
  patience: 15  # Early stopping
  early_stopping_metric: 'f1'  # Metric for early stopping; Options: 'loss', 'f1', 'auc', null (default; use 'loss')
  # epochs: 35
  threshold_metric: null  # Threshold optimization metric; Options: 'f1', 'f0.5', 'f2', null (default; use 0.5)
