# Flu A Learning Plateau Analysis Bundle
# Purpose: Understand when and why learning stops improving
# Extended training to observe full learning curve and identify plateau point
defaults:
  - /virus: flu_a
  - /paths: flu_a
  - /embeddings: default
  - /dataset: default
  - /training: base
  - _self_

# ====================================================================
# DIRECTORY NAMING
# ====================================================================
# Manual run_suffix to distinguish plateau analysis runs
run_suffix: "_seed_42_isolates_100_plateau_analysis"

# ====================================================================
# SEED MANAGEMENT
# ====================================================================
master_seed: 42

process_seeds:
  preprocessing: null
  embeddings: null
  dataset: null
  training: null
  evaluation: null

# ====================================================================
# PROTEIN SELECTION
# ====================================================================
virus:
  selected_functions:
    - "RNA-dependent RNA polymerase PB2 subunit"  # PB2 - Segment 1
    - "RNA-dependent RNA polymerase catalytic core PB1 subunit"  # PB1 - Segment 2
    - "RNA-dependent RNA polymerase PA subunit"  # PA - Segment 3

# ====================================================================
# MODEL AND DATASET OVERRIDES
# ====================================================================
# Embeddings overrides
embeddings:
  batch_size: 96
  use_selected_only: false  # Compute embeddings for selected_functions (PB1+PB2+PA)

# Dataset overrides - Same size as learning test for comparison
dataset:
  use_selected_only: true  # Use selected_functions (a subset of protein functions)
  neg_to_pos_ratio: 1.0  # Ratio of negative to positive pairs; default is 3.0
  allow_same_func_negatives: false  # No same-function negative pairs
  max_same_func_ratio: 0.5  # Not used when allow_same_func_negatives=false
  max_isolates_to_process: 700  # Larger dataset to observe plateau more clearly
  train_ratio: 0.8
  val_ratio: 0.1

# Training overrides - Extended training to observe plateau
training:
  use_diff: true
  use_prod: true
  batch_size: 16
  learning_rate: 0.001
  epochs: 100  # Many epochs to observe full learning curve
  patience: 20  # High patience to see plateau clearly
  dropout: 0.3  # Normal regularization
  early_stopping_metric: 'f1'  # Monitor F1 score
  threshold_metric: null  # Use default 0.5 threshold for simplicity

