# Flu A bundle (PB1, PB2, PA proteins - 3 proteins)
# Contains virus-specific overrides for 3-protein experiments
defaults:
  - /virus: flu_a
  - /paths: flu_a
  - /embeddings: default
  - /dataset: default
  - /training: base
  - _self_

# ====================================================================
# EXPERIMENT IDENTIFICATION
# ====================================================================
# Optional manual directory suffix - set this to create a specific output directory
# This creates: data/processed/flu_a/July_2025_seed_42_GTOs_2000_pb1_pb2/

# run_suffix: "_seed_42_GTOs_5000_pb1_pb2_pa"

# ====================================================================
# SEED MANAGEMENT
# ====================================================================
master_seed: 42

process_seeds:
  preprocessing: null
  embeddings: null
  dataset: null
  training: null
  evaluation: null

# ====================================================================
# DATA SAMPLING
# ====================================================================
# max_files_to_process: null  # Dataset subset
# max_isolates_to_process: 5000  # Limit number of isolates to process (pipeline-wide)
max_isolates_to_process: 1000  # Limit number of isolates to process (pipeline-wide)

# ====================================================================
# PROTEIN SELECTION
# ====================================================================
# Override selected_functions to include only PB1 and PB2
virus:
  selected_functions:
    - "RNA-dependent RNA polymerase PB2 subunit"  # PB2 - Segment 1
    - "RNA-dependent RNA polymerase catalytic core PB1 subunit"  # PB1 - Segment 2
    - "RNA-dependent RNA polymerase PA subunit"  # PA - Segment 3

# ====================================================================
# MODEL AND DATASET OVERRIDES
# ====================================================================
embeddings:
  # batch_size: 16
  batch_size: 32
  use_selected_only: true  # Use selected_functions for PB1+PB2+PA

dataset:
  use_selected_only: true  # Use selected_functions
  neg_to_pos_ratio: 1.0  # Ratio of negative to positive pairs
  allow_same_func_negatives: true  # Allow same-function negative pairs
  max_same_func_ratio: 0.5  # Maximum fraction of same-function negative pairs

training:
  batch_size: 16
  learning_rate: 0.001
  patience: 10  # Early stopping patience