# Flu A experiment: All 9 core proteins
# Baseline experiment with all core structural proteins
defaults:
  - /virus: flu_a
  - /embeddings: default
  - /dataset: default
  - /training: base
  - _self_

# ==============================================================================
# EXPERIMENT IDENTIFICATION
# ==============================================================================
# Manual directory suffix - set this to create a specific output directory
# This creates: data/processed/flu_a/July_2025_seed_42_GTOs_2000_all_core/
run_suffix: "_seed_42_GTOs_2000_all_core"

# ==============================================================================
# SEED MANAGEMENT
# ==============================================================================
master_seed: 42

process_seeds:
  preprocessing: null
  embeddings: null
  dataset: null
  training: null
  evaluation: null

# ==============================================================================
# DATA SAMPLING
# ==============================================================================
max_files_to_process: 2000

# ==============================================================================
# PROTEIN SELECTION
# ==============================================================================
# Use all core functions (from virus/flu_a.yaml: core_functions)
virus:
  selected_functions: ${virus.core_functions}

# ==============================================================================
# MODEL SETTINGS
# ==============================================================================
embeddings:
  batch_size: 16
  use_selected_only: true  # Use selected_functions for all core

dataset:
  use_selected_only: true  # Use selected_functions for all core experiment

training:
  batch_size: 128
