# Flu metadata filtering experiment
# Filter isolates to Human + H3N2 + 2024 before creating train/val/test splits.
#
# Inherit the default Flu task (currently HA/NA selection etc.) from `flu.yaml`.

defaults:
  - flu
  - _self_

dataset:
  host: "Human"
  year: 2024
  hn_subtype: "H3N2"

training:
  batch_size: 256
