# Flu A Learning Verification Bundle
# Purpose: Verify that the model actually learns from data (Karpathy-style sanity checks)
# This uses a very small dataset to quickly verify learning behavior
# Based on: https://karpathy.github.io/2019/04/25/recipe/
defaults:
  - /virus: flu_a
  - /paths: flu_a
  - /embeddings: default
  - /dataset: default
  - /training: base
  - _self_

# ====================================================================
# DIRECTORY NAMING
# ====================================================================
# Manual run_suffix to distinguish learning test runs from regular runs
# Without this, it would auto-generate to "_seed_42_isolates_100" which
# would conflict with a regular 100-isolate experiment
run_suffix: "_seed_42_isolates_100_learning_test"

# ====================================================================
# SEED MANAGEMENT
# ====================================================================
master_seed: 42

process_seeds:
  preprocessing: null
  embeddings: null
  dataset: null
  training: null
  evaluation: null

# ====================================================================
# PROTEIN SELECTION
# ====================================================================
virus:
  selected_functions:
    - "RNA-dependent RNA polymerase PB2 subunit"  # PB2 - Segment 1
    - "RNA-dependent RNA polymerase catalytic core PB1 subunit"  # PB1 - Segment 2
    - "RNA-dependent RNA polymerase PA subunit"  # PA - Segment 3

# ====================================================================
# MODEL AND DATASET OVERRIDES
# ====================================================================
# Embeddings overrides
embeddings:
  batch_size: 96
  use_selected_only: false  # Compute embeddings for selected_functions (PB1+PB2+PA)

# Dataset overrides - VERY SMALL for learning verification
dataset:
  use_selected_only: true  # Use selected_functions (a subset of protein functions)
  neg_to_pos_ratio: 1.0  # Ratio of negative to positive pairs; default is 3.0
  allow_same_func_negatives: false  # No same-function negative pairs
  max_same_func_ratio: 0.5  # Not used when allow_same_func_negatives=false
  max_isolates_to_process: 100  # VERY SMALL - should overfit quickly if learning works
  train_ratio: 0.8
  val_ratio: 0.1

# Training overrides - Minimal epochs to detect random behavior
training:
  use_diff: true
  use_prod: true
  epochs: 10  # Very few epochs - if model learns, should see improvement quickly
  patience: 3  # Low patience - stop quickly once learning plateaus
  batch_size: 16
  learning_rate: 0.001
  early_stopping_metric: 'f1'  # Monitor F1 score
  threshold_metric: null  # Use default 0.5 threshold for simplicity

