# Flu bundle - PB2, PB1, PA proteins only (conserved segments)
# Experiment: Label-shuffle sanity test
# This shuffles training labels to verify the model is learning genuine patterns
# Isolates: 5K, no same-function negatives
defaults:
  - /virus: flu
  - /paths: flu
  - /embeddings: default
  - /dataset: default
  - /training: base
  - _self_

# ====================================================================
# DIRECTORY NAMING
# ====================================================================
run_suffix: null

# ====================================================================
# SEED MANAGEMENT
# ====================================================================
master_seed: 42

process_seeds:
  preprocessing: null
  embeddings: null
  dataset: null
  training: null
  evaluation: null

# ====================================================================
# PROTEIN SELECTION
# ====================================================================
virus:
  selected_functions:
    - "RNA-dependent RNA polymerase PB2 subunit"  # PB2 (Segment 1)
    - "RNA-dependent RNA polymerase catalytic core PB1 subunit"  # PB1 (Segment 2)
    - "RNA-dependent RNA polymerase PA subunit"  # PA (Segment 3)

# ====================================================================
# MODEL AND DATASET OVERRIDES
# ====================================================================
# Embeddings overrides
embeddings:
  batch_size: 96

# Dataset overrides
dataset:
  use_selected_only: true  # Use selected_functions (a subset of protein functions)
  neg_to_pos_ratio: 1.0  # Ratio of negative to positive pairs; default is 1.0
  allow_same_func_negatives: false  # Whether to allow same-function negative pairs
  max_same_func_ratio: 0.5  # Maximum fraction of same-function negative pairs
  max_isolates_to_process: 5000  # null = full dataset, or set to 100, 500, etc.
  shuffle_train_labels: true  # SANITY TEST: Shuffle training labels
  shuffle_train_labels_seed: 42  # Seed for reproducible label shuffling

# Training overrides
training:
  # epochs: 35
  patience: 15  # Early stopping
  batch_size: 16
  learning_rate: 0.001
  early_stopping_metric: 'f1'  # Monitor F1 score
  threshold_metric: null  # Use default 0.5 threshold for simplicity
