# Flu Learning Plateau Analysis Bundle
# Experiment: Understand when and why learning stops improving
defaults:
  - /virus: flu
  - /paths: flu
  - /embeddings: default
  - /dataset: default
  - /training: base
  - _self_

# ====================================================================
# DIRECTORY NAMING
# ====================================================================
# Note: run_suffix should be null to use shared preprocessing
run_suffix: null

# ====================================================================
# SEED MANAGEMENT
# ====================================================================
master_seed: 42

process_seeds:
  preprocessing: null
  embeddings: null
  dataset: null
  training: null
  evaluation: null

# ====================================================================
# PROTEIN SELECTION
# ====================================================================
virus:
  selected_functions:
    - "RNA-dependent RNA polymerase PB2 subunit"  # PB2 (Segment 1)
    - "RNA-dependent RNA polymerase catalytic core PB1 subunit"  # PB1 (Segment 2)
    - "RNA-dependent RNA polymerase PA subunit"  # PA (Segment 3)

# ====================================================================
# MODEL AND DATASET OVERRIDES
# ====================================================================
# Embeddings overrides
embeddings:
  batch_size: 96

# Dataset overrides
dataset:
  use_selected_only: true  # Use selected_functions (a subset of protein functions)
  neg_to_pos_ratio: 1.0  # Ratio of negative to positive pairs; default is 3.0
  allow_same_func_negatives: false  # Whether to allow same-function negative pairs
  max_same_func_ratio: 0.5  # Maximum fraction of same-function negative pairs
  max_isolates_to_process: 1000  # Larger dataset to observe plateau more clearly

# Training overrides
training:
  epochs: 50  # Many epochs to observe full learning curve
  patience: 40  # High patience to see plateau clearly
  batch_size: 16
  learning_rate: 0.001
  early_stopping_metric: 'f1'  # Monitor F1 score
  threshold_metric: null  # Use default 0.5 threshold for simplicity
  dropout: 0.2  # Normal regularization
  use_diff: false
  use_prod: false
