# Flu A bundle - with training and virus-specific overrides
defaults:
  - /virus: flu_a
  - /embeddings: default
  - /training: base
  - _self_  # Bundle overrides loaded AFTER base configs

# Experiment-level settings
master_seed: null
max_files_to_process: null  # null = process all files
# max_files_to_process: 100  # null = process all files
run_suffix: null  # Optional suffix for run directories (e.g., '_subset_5k', '_v2')

# Process-specific seeds (null = use derived from master_seed)
process_seeds:
  preprocessing: null
  embeddings: 42
  dataset: null
  training: null
  evaluation: null

# Virus-specific embeddings overrides
embeddings:
  batch_size: 16

# Virus-specific training overrides
training:
  batch_size: 128  # Use smaller batches for longer sequences
