# Base training configuration (reusable)
batch_size: 16
learning_rate: 0.001 # 1e-3
epochs: 100
optimizer: 'adam'

# Model architecture
hidden_dims: [512, 256, 64]
dropout: 0.3
use_diff: false # Use absolute difference |A - B| as interaction feature (boolean)
use_prod: false # Use element-wise product A * B as interaction feature (boolean)

# Training control
patience: 15  # Early stopping patience
early_stopping_metric: 'f1'  # Metric for early stopping: 'loss' (lower is better), 'f1' and 'auc' (higher is better)
threshold_metric: null  # Threshold optimization metric; null (no optimization; use 0.5), 'f1' (default), 'f0.5' (emphasize precision), 'f2' (emphasize recall); This metric is used to determine the threshold for the binary classifier; the threshold is the metric value that is used to classify the pairs as positive or negative
